#!/usr/bin/env perl
use 5.036;
use utf8;
use open ':std', ':encoding(UTF-8)';
use Sq;
use Sq::Sig;
use Path::Tiny qw(path);

# read info about examples
my $info =
    Sq->fs->read_text(path('examples', 'info.txt'))
    ->regex_match(qr/\A(\S+) \s+ (.+) $/x)
    ->to_hash(sub($kv) { $kv->[0], $kv->[1] });

# show all examples with info
my $examples =
    Sq->fs->children('examples')
    ->keep(call 'is_file')
    ->sort(by_str)
    ->choose(sub($file) {
        my $name = $file->basename;
        return None if $name eq 'info.txt';
        return Some(sq [$name, $info->get($name)->or("")]);
    });

Sq->fmt->table({
    header => [qw/Script Description/],
    data   => $examples,
});
