---
abstract: 'The Sq language'
author:
  - 'David Raab <davidraab83@gmail.com>'
build_requires:
  List::Util: '0'
  Path::Tiny: '0'
  Test2::V0: '0.000156'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Sq
provides:
  Array:
    file: lib/Sq/Collections/Array.pm
  Hash:
    file: lib/Sq/Collections/Hash.pm
  Heap:
    file: lib/Sq/Collections/Heap.pm
  List:
    file: lib/Sq/Collections/List.pm
  Measure:
    file: lib/Sq/Core/Measure.pm
  Option:
    file: lib/Sq/Core/Option.pm
  Queue:
    file: lib/Sq/Collections/Queue.pm
  Result:
    file: lib/Sq/Core/Result.pm
  Seq:
    file: lib/Sq/Collections/Seq.pm
  Sq:
    file: lib/Sq.pm
    version: '0.006'
  Sq::Io:
    file: lib/Sq/Io.pm
requires:
  Carp: '0'
  Sub::Exporter: '0'
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: '0.006'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
