package Sq::Sig::Parser;
use 5.036;
use Sq;
use Sq::Type;
use Sq::Signature;

my $int     = t_int;
my $parser  = t_sub;
my $sub     = t_sub;
my $str     = t_str;
my $regex   = t_regex;
my $parsers = t_array(t_of $parser);
my $astr1   = t_array(t_min(1), t_of $str);
my $split   = t_or($str, $regex);

sig ('Sq::Parser::p_run',        $parser, $str,                    t_opt);
sig ('Sq::Parser::p_valid',      $parser, $str,                   t_bool);
sig ('Sq::Parser::p_match',      $regex,                          $parser);
sig ('Sq::Parser::p_matchf',     $regex, $sub,                    $parser);
sig ('Sq::Parser::p_matchf_opt', $regex, $sub,                    $parser);
sigt('Sq::Parser::p_map',        t_tuplev($sub, $parsers),        $parser);
sig ('Sq::Parser::p_bind',       $parser, $sub,                   $parser);
sigt('Sq::Parser::p_and',        $parsers,                        $parser);
sigt('Sq::Parser::p_return',     t_array,                         $parser);
sigt('Sq::Parser::p_or',         $parsers,                        $parser);
sigt('Sq::Parser::p_maybe',      $parsers,                        $parser);
sig ('Sq::Parser::p_join',       $str, $parser,                   $parser);
sigt('Sq::Parser::p_str',        $astr1,                          $parser);
sigt('Sq::Parser::p_strc',       $astr1,                          $parser);
sigt('Sq::Parser::p_many',       $parsers,                        $parser);
sigt('Sq::Parser::p_many0',      $parsers,                        $parser);
sig ('Sq::Parser::p_ignore',     $parser,                         $parser);
sig ('Sq::Parser::p_fail',                                        $parser);
sig ('Sq::Parser::p_qty',        $int, $int, $parser,             $parser);
sig ('Sq::Parser::p_choose',     $parser, $sub,                   $parser);
sig ('Sq::Parser::p_repeat',     $int, $parser,                   $parser);
sig ('Sq::Parser::p_keep',       $parser, $sub,                   $parser);
sig ('Sq::Parser::p_split',      $split, $parser,                 $parser);
sig ('Sq::Parser::p_delay',      $sub,                            $parser);
sig ('Sq::Parser::p_not',        $parser,                         $parser);
sig ('Sq::Parser::p_empty',                                       $parser);

1;