=encoding UTF-8

=head1 Sq::Exporter

Use it in a module.

    package MyModule;
    use 5.036;
    use Sq::Exporter;
    our $SIGNATURE = 'Sig/MyModule.pm';
    our @EXPORT    = qw(this that);

    sub this() { ... }
    sub that() { ... }

Import wherever you need.

    # import nothing
    use MyModule ();

    # import all
    use MyModule;

    # only import 'this'
    use MyModule qw(this);

    # load signature, then import all functions
    use MyModule -sig => 1;

    # load signature, only import "this"
    use MyModule -sig => 1, 'this';
