=encoding UTF-8

=head1 Sq::Manual

This is an overview of already written documentation.

=head2 Sequence or Array

In L<Sequence or Array|file:///lib/Sq/Manual/SeqOrArray.pod> I compare `Array`
and `Seq` and describe it's advantages and when you should use `Seq`.

=head2 API Documentation

=head2 Other

=head3 L<Sq::Manual::FromSub>

An in-depth tutorial on how to use Seq->fromSub to create your own
constructor functions and make other Perl Code / Modules work with
Seq.

=head2 DESIGN

=over 4

=item * L<Sq::Manual::Design::Wrap>

Describes why certain operations like C<< Seq->wrap >> stops at C<undef>

=item * L<Sq::Manual::Design::MinMax>

Describes why functions like C<Sq::max> uses a mandatory C<$default> argument.

=back
