=encoding UTF-8

=head1 Sq::Parser

A Combinator based approach to parsing. The parser is not yet complet. It
works and it can parse stuff, but currently lacks any kind of useful error
messages when parsing is not succesfull.

This will improve in the future, also some more functions will be added.
Still the API in itself will not change much.

When you are used with Regexes and I guess you are when you are a Perl programmer
you will see the similarity with a Regex based approach. But the Combinator here
is designed to just use Perl Regexes with Parsing.

See L<Sq::Manual::Parser::Intro> at the moment for an Intro.

=head1 CONSTRUCTORS


=head2 parser


=head1 RUNNERS


=head2 p_run

=head2 p_valid


=head1 PARSERS


=head2 REGEX

=head3 p_match

=head3 p_matchf

=head3 p_matchf_opt


=head2 SPECIAL

=head3 p_map

=head3 p_bind

=head3 p_return

=head3 p_and

=head3 p_fail

=head3 p_empty

=head2 STRING

=head3 p_str

=head3 p_strc

=head3 p_join

=head3 p_split


=head2 COMBINATORS

=head3 p_and

=head3 p_or

=head3 p_maybe

=head3 p_many

=head3 p_many0

=head3 p_ignore

=head3 p_qty

=head3 p_choose

=head3 p_repeat

=head3 p_keep

=head3 p_not

=head3 p_delay

