=encoding UTF-8

=head1 Sq::Reflection

Module that contains function to manipulate or query Perl's symbol-table.
Is automatically loaded when loading C<Sq>.

Nothing is exported at the moment. So all functions must be called with
`Sq::Reflection::` at the moment. This will change as soon exporting
is finished.

=head1 Functions

=head2 has_func($package, $name) : $bool

Returns a truish value if a package has a function defined.

    my $bool = has_func('Array', 'newShiny');

=head2 get_func($func_name) : $sub | EXCEPTION

Write a function with full package name and get back the subroutine
reference. When the function you want to read does not exists, it throws
an exception.

    my $map = get_func('Array::map');

=head2 set_func($func_name, $sub) : void

Sets a function to a new function by providing the subroutine reference.

    my $orig = get_func('Array::map');

    set_func('Array::map' => sub($array, $sub) {
        warn "Array::map was called!\n";
        return $orig->($array, $sub);
    });

=head2 funcs_of($package) : $array_of_func_names

Returns all function names of a package as an Sq Array.

    my $funcs = funcs_of('Array');

=head2 signatures() : $array_of_funcs

Returns all functions for which a signature with C<sig> and C<sigt> from
C<Sq::Signature> was added.


